GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/61d503121a9056115a7f86bb

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Sherlock Holmes",
  "number": "123-456-7890"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Sherlock Holmes"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "number": "123-456-7890"
}

###
PUT http://localhost:3001/api/persons/61d62ed63e7e6fc0ac9da310
Content-Type: application/json

{
  "name": "Sherlock Holmes",
  "number": "111-222-3333"
}

###
DELETE http://localhost:3001/api/persons/61d503121a9056115a7f86bb

###
GET http://localhost:3001/info